### ISSUE TITLE
English Translation?

### ISSUE THREAD

**Issue by howardroark2018** [savokiss/layoutit#1]
Hi, Thanks for the efforts to put up this wonderful code on github.
However, I have been facing a critical issue here. I don't understand chinese, so I am unable to use it. Is there an english version that you point me to or maybe, is there any other way you could probably help me out? As I suppose I won't be the only one here who requires an english translation, I guess, it would be as good for many others like me.

Thanks again! :)

**Comment by savokiss** [comment]
I'll figure it out in a few days.And most of the effort is the menu translation, if you are in a hurry ,you could see the  [getbootstrap](http://getbootstrap.com)  to find the same component and get the name or ask me here~

**Comment by savokiss** [comment]
I just translated it in another `index.html` and it served here: [layoutit/en](http://savokiss.me/layoutit/en)

Closing this.

**Comment by howardroark2018** [comment]
Thank you so much for a quick response, specially when it is so rate that github project dudes reply so quickly. And, thanking you so much for letting me know and deciding to do something about the translation. Yes, I have been trying to go the way suggested by you, but For me, Chinese is like greek, I don't understand anything about it. After-all, there's a reason it's considered one of the toughest language in the world, the only Competitor being perhaps Japanese. Been trying to find and replace the language parts and it is no doubt crazy. Besides the menu, there are a lot of parts intimately connected to it, like popups and even the  content blocks.. etc. I am in no hurry as such, but if I do end up doing it myself, someday that is, I would like to share it with the code. For now my best chance, is to wait patiently for what you have planned. :)

**Comment by howardroark2018** [comment]
OH! I posted the comment via mail, without seeing your last comment, my bad!

**Comment by howardroark2018** [comment]
@savokiss WoW! Thank you sso much!!! :D

**Comment by savokiss** [comment]
Glad to help ~ :)
