### ISSUE TITLE
Found 2 elements with non-unique id #exampleInputEmail1

### ISSUE THREAD

**Issue by sharmaanand086** [savokiss/layoutit#3]
when i drag the form element to the droppable position am getting this error in image below 
![image](https://user-images.githubusercontent.com/38725515/44320325-f4752880-a45e-11e8-8481-318f2db13af5.png)

thank you

**Comment by sharmaanand086** [comment]
hey anyone help me please thank you in advance ..
when am dragging the gettting duplicate errror 
![image](https://user-images.githubusercontent.com/38725515/44445443-90896600-a5fe-11e8-88a9-a9c610d2b1db.png)
 
but when am inspecting the same not haveing any duplicate id 
add some answer .
![image](https://user-images.githubusercontent.com/38725515/44445424-823b4a00-a5fe-11e8-9080-ff985ddaf5dc.png)

**Comment by savokiss** [comment]
Hey, I could see the error too, but I think you can just ignore this error, It is much more like a warning for developers.

**Comment by sharmaanand086** [comment]
hello savokiss thank for info but i have to add counter drag element from this above error 
am getting my counter working when i fix it without drag
![image](https://user-images.githubusercontent.com/38725515/44456517-6051bf80-a61e-11e8-89fc-520e4bd7f882.png)

but when am doing it same with the drag and drop am getting error  as above i said how do solve this error 
countdown.js:6 Uncaught TypeError: Cannot read property 'value' of null
    at settimer (countdown.js:6)
    at HTMLInputElement.onclick (index.php:1)
